
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mavenwebapp-ds
  labels:
    name: mavenwebapp
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: webapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcontainer
        image: user593/maven-web-app:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
spec:
  type: NodePort
  selector:
    name: mavenwebapp
  ports:
  - port: 8080
    targetPort: 8080
