apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapp-dp
  labels:
    name: mavenwebapp
  namespace: test-ns
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: webapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcontainer
        image: dockerhandson/maven-web-application:2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
spec:
  type: NodePort
  selector:
    name: mavenwebapp
  ports:
  - port: 8080
    targetPort: 8080
