apiVersion: v1
kind: Pod
metadata:
  name: mavenwebapp
  labels:
    app: mavenwebapp
  namespace: test-ns
spec:
  containers:
  - name: mavenwebapp
    image: dockerhandson/maven-web-application:1
    ports:
    - containerPort: 8080
