apiVersion: v1
kind: ReplicationController
metadata:
  name: mavenrc
  labels:
    app: mavenwebappsvc
  namespace: test-ns
spec:
  replicas: 2
  selector:
    app: mavenwebappsvc
  template:
    metadata:
      name: mavenwebapp
      labels:
        app: mavenwebappsvc
    spec:
      containers:
      - name: mavenwebapp
        image: dockerhandson/maven-web-application:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: mavenwebappsvc
  ports:
  - port: 80
    targetPort: 8080
