apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mavenwebapp-rs
  labels:
    app: mavenwebapp
  namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: webapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcontainer
        image: user593/maven-web-app:1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
spec:
  type: NodePort
  selector:
    app: mavenwebapp
  ports:
  - port: 8080
    targetPort: 8080
