apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: test-ns
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "2"
    limits.memory: "4Gi"
    pods: "2"
    count/deployments.apps: 1
