apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebapp-dp
  labels:
    name: mavenwebapp
  namespace: test-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mavenwebapp
  template:
    metadata:
      name: webapppod
      labels:
        app: mavenwebapp
    spec:
      containers:
      - name: mavenwebappcontainer
        image: user593/maven-web-app:1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "512m"
          limits:
            memory: "512Mi"
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
spec:
  type: NodePort
  selector:
    name: mavenwebapp
  ports:
  - port: 8080
    targetPort: 8080
