apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    app: nginxpod
  namespace: test-ns
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  type: ClusterIP
  selector:
    app: nginxpod
  ports:
    - port: 80
      targetPort: 80
