apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenwebappdp
  labels:
    app: mavenwebappdp
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mavenwebappdp
  template:
    metadata:
      labels:
        app: mavenwebappdp
    spec:
      imagePullSecrets:
      - name: dockerhub
      containers:
      - name: mavenwebappdp
        image: user593/maven-web-app:1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 400m
            memory: 256Mi
          limits:
            cpu: 1
            memory: 1Gi
        volumeMounts:
        - name: tomcatconfig
          mountPath: "/usr/local/tomcat/conf/tomcat-users.xml"
          subPath: "tomcat-users.xml"
      volumes:
      - name: tomcatconfig
        configMap:
          name: mavenwebappconfig
          items:
          - key: "tomcat-users.xml"
            path: "tomcat-users.xml"
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappdp
  namespace: test-ns
  labels:
    app: mavenwebappdp
spec:
  type: NodePort
  selector:
    app: mavenwebappdp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30030
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mavenwebappconfig
  namespace: test-ns
data:
  tomcat-users.xml: |
    <tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">
     <user username="admin" password="admin123" roles="admin-gui"/>
    </tomcat-users>
