apiVersion: v1
kind: ConfigMap
metadata:
  name: springappconfig
  namespace: test-ns
data:
  dbusername: devdb
---
apiVersion: v1
kind: Secret
metadata:
  name: springappsecret
  namespace: test-ns
type: Opaque
stringData:
  dbpassword: devdb@123
